# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  branches:
    include:
      - "*"

jobs:
  # 1st JOB
  - job: build_example
    displayName: These tasks will run using a custom image

    pool: Custom
    container: 
      image: docker-hts.repo.east1.ncloud.netapp.com/codeql-v/codeql-agent:latest
      endpoint: docker-hts.repo.east1.ncloud.netapp.com

    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        mavenOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.8'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        goals: 'package'
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: 'ls'
    - task: AdvancedSecurity-Codeql-Init@1
      inputs:
        languages: 'javascript'
        querysuite: 'code-scanning'
        codeqltoolsdirectory: '/azp/_work/_tool/'



