# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  branches:
    include:
      - "*"

jobs:
  - job: build_example
    displayName: These tasks will run using a custom image

    pool: Custom
    container: 
      image: docker-hts.repo.east1.ncloud.netapp.com/codeql/codeql-agent:latest
      endpoint: docker-hts.repo.east1.ncloud.netapp.com

    steps:
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          echo "Listing current directory:"
          ls -la
          echo "Listing /azp/_work/_tool/ directory:"
          ls -la /azp/_work/_tool/
          
    - task: AdvancedSecurity-Codeql-Init@1
      inputs:
        languages: 'java'
        querysuite: 'code-scanning'
        codeqltoolsdirectory: '/azp/_work/_tool/CodeQL'
        loglevel: '1'

    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        mavenOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.11'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        goals: 'package'

    - task: AdvancedSecurity-Codeql-Analyze@1




